"""empty message

Revision ID: 31beba82c0c0
Revises: e8cd6f33aac5
Create Date: 2020-03-12 07:22:00.964384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31beba82c0c0'
down_revision = 'e8cd6f33aac5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('seeking_description', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'seeking_description')
    # ### end Alembic commands ###
