"""empty message

Revision ID: 3bd5ab553a00
Revises: bdc49b13f074
Create Date: 2020-03-14 08:38:40.537071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bd5ab553a00'
down_revision = 'bdc49b13f074'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Genre', 'artist_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('Genre', 'venue_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Genre', 'venue_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('Genre', 'artist_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
