"""empty message

Revision ID: 6c3a7d87de79
Revises: a5f3ac3b076f
Create Date: 2020-03-14 08:25:05.784838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c3a7d87de79'
down_revision = 'a5f3ac3b076f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('genre_items')
    op.add_column('Genre', sa.Column('artist_id', sa.Integer(), nullable=False))
    op.add_column('Genre', sa.Column('venue_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'Genre', 'Venue', ['venue_id'], ['id'])
    op.create_foreign_key(None, 'Genre', 'Artist', ['artist_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Genre', type_='foreignkey')
    op.drop_constraint(None, 'Genre', type_='foreignkey')
    op.drop_column('Genre', 'venue_id')
    op.drop_column('Genre', 'artist_id')
    op.create_table('genre_items',
    sa.Column('genre_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('venue_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('artist_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], name='genre_items_artist_id_fkey'),
    sa.ForeignKeyConstraint(['genre_id'], ['Genre.id'], name='genre_items_genre_id_fkey'),
    sa.ForeignKeyConstraint(['venue_id'], ['Venue.id'], name='genre_items_venue_id_fkey'),
    sa.PrimaryKeyConstraint('genre_id', 'venue_id', 'artist_id', name='genre_items_pkey')
    )
    # ### end Alembic commands ###
