"""empty message

Revision ID: a075af6cb2a8
Revises: c0265061b224
Create Date: 2020-03-14 10:31:07.534128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a075af6cb2a8'
down_revision = 'c0265061b224'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.create_foreign_key(None, 'Artist', 'Genre', ['genres'], ['artist_id'])
    #op.create_foreign_key(None, 'Venue', 'Genre', ['genres'], ['venue_id'])
    # ### end Alembic commands ###
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Venue', type_='foreignkey')
    op.drop_constraint(None, 'Artist', type_='foreignkey')
    # ### end Alembic commands ###
