"""empty message

Revision ID: a5f3ac3b076f
Revises: acb272106dce
Create Date: 2020-03-14 08:22:13.618221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5f3ac3b076f'
down_revision = 'acb272106dce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genre_items',
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], ),
    sa.ForeignKeyConstraint(['genre_id'], ['Genre.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['Venue.id'], ),
    sa.PrimaryKeyConstraint('genre_id', 'venue_id', 'artist_id')
    )
    op.drop_constraint('Genre_venue_id_fkey', 'Genre', type_='foreignkey')
    op.drop_column('Genre', 'venue_id')
    op.add_column('UpcomingShow', sa.Column('artist_id', sa.Integer(), nullable=True))
    op.add_column('UpcomingShow', sa.Column('venue_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'UpcomingShow', 'Artist', ['artist_id'], ['id'])
    op.create_foreign_key(None, 'UpcomingShow', 'Venue', ['venue_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'UpcomingShow', type_='foreignkey')
    op.drop_constraint(None, 'UpcomingShow', type_='foreignkey')
    op.drop_column('UpcomingShow', 'venue_id')
    op.drop_column('UpcomingShow', 'artist_id')
    op.add_column('Genre', sa.Column('venue_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('Genre_venue_id_fkey', 'Genre', 'Venue', ['venue_id'], ['id'])
    op.drop_table('genre_items')
    # ### end Alembic commands ###
