"""empty message

Revision ID: acb272106dce
Revises: 31beba82c0c0
Create Date: 2020-03-12 07:31:24.576729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acb272106dce'
down_revision = '31beba82c0c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Artist', 'past_shows',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('Artist', 'upcoming_shows',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('Venue', 'past_shows',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('Venue', 'upcoming_shows',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Venue', 'upcoming_shows',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('Venue', 'past_shows',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('Artist', 'upcoming_shows',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('Artist', 'past_shows',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
