"""empty message

Revision ID: bad4f7376db0
Revises: 3bd5ab553a00
Create Date: 2020-03-14 08:41:30.252902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bad4f7376db0'
down_revision = '3bd5ab553a00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Artist_genres_fkey', 'Artist', type_='foreignkey')
    op.create_foreign_key(None, 'Artist', 'Genre', ['genres'], ['artist_id'])
    op.drop_constraint('Venue_genres_fkey', 'Venue', type_='foreignkey')
    op.create_foreign_key(None, 'Venue', 'Genre', ['genres'], ['venue_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Venue', type_='foreignkey')
    op.create_foreign_key('Venue_genres_fkey', 'Venue', 'Genre', ['genres'], ['id'])
    op.drop_constraint(None, 'Artist', type_='foreignkey')
    op.create_foreign_key('Artist_genres_fkey', 'Artist', 'Genre', ['genres'], ['id'])
    # ### end Alembic commands ###
