"""empty message

Revision ID: bdc49b13f074
Revises: bf3438987d1c
Create Date: 2020-03-14 08:33:12.760482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdc49b13f074'
down_revision = 'bf3438987d1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('genres', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Artist', 'Genre', ['genres'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Artist', type_='foreignkey')
    op.drop_column('Artist', 'genres')
    # ### end Alembic commands ###
