"""empty message

Revision ID: bf3438987d1c
Revises: 6c3a7d87de79
Create Date: 2020-03-14 08:26:48.660575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf3438987d1c'
down_revision = '6c3a7d87de79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'Artist', 'Genre', ['genres'], ['id'])
    op.add_column('Venue', sa.Column('genres', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Venue', 'Genre', ['genres'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Venue', type_='foreignkey')
    op.drop_column('Venue', 'genres')
    op.drop_constraint(None, 'Artist', type_='foreignkey')
    # ### end Alembic commands ###
