"""empty message

Revision ID: c0265061b224
Revises: bad4f7376db0
Create Date: 2020-03-14 10:08:56.590335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0265061b224'
down_revision = 'bad4f7376db0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.create_foreign_key(None, 'Artist', 'Genre', ['genres'], ['artist_id'])
    op.create_foreign_key(None, 'Genre', 'Venue', ['venue_id'], ['id'])
    op.create_foreign_key(None, 'Genre', 'Artist', ['artist_id'], ['id'])
    #op.create_foreign_key(None, 'Venue', 'Genre', ['genres'], ['venue_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Venue', type_='foreignkey')
    op.drop_constraint(None, 'Genre', type_='foreignkey')
    op.drop_constraint(None, 'Genre', type_='foreignkey')
    op.drop_constraint(None, 'Artist', type_='foreignkey')
    # ### end Alembic commands ###
