"""empty message

Revision ID: e8588c822895
Revises: a075af6cb2a8
Create Date: 2020-03-14 10:35:59.354999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8588c822895'
down_revision = 'a075af6cb2a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Genre_artist_id_fkey', 'Genre', type_='foreignkey')
    op.drop_constraint('Genre_venue_id_fkey', 'Genre', type_='foreignkey')
    op.drop_column('Genre', 'artist_id')
    op.drop_column('Genre', 'venue_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Genre', sa.Column('venue_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('Genre', sa.Column('artist_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('Genre_venue_id_fkey', 'Genre', 'Venue', ['venue_id'], ['id'])
    op.create_foreign_key('Genre_artist_id_fkey', 'Genre', 'Artist', ['artist_id'], ['id'])
    # ### end Alembic commands ###
